export enum AddLinkActionTypes {
  ADD_LINK_DATA = 'ADD_LINK_DATA',
  ADD_LINK_SUCCESS = 'ADD_LINK_SUCCESS',
  ADD_LINK_FAILED = 'ADD_LINK_FAILED',
}

export enum GetCurrentUserActionTypes {
  GET_CURRENT_USER_DATA = 'GET_CURRENT_USER_DATA',
  GET_CURRENT_USER_FAILED = 'GET_CURRENT_USER_FAILED',
  GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS',
}

export enum AuthorizeActionTypes {
  AUTHORIZE_USER_SUCCESS = 'AUTHORIZE_USER_SUCCESS',
  AUTHORIZE_USER_DATA = 'AUTHORIZE_USER_DATA',
  AUTHORIZE_USER_FAILED = 'AUTHORIZE_USER_FAILED',
}

export enum LogoutActionType {
  LOGOUT_USER = 'LOGOUT_USER',
}

export enum RegisterActionTypes {
  REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS',
  REGISTER_USER_DATA = 'REGISTER_USER_DATA',
  REGISTER_USER_FAILED = 'REGISTER_USER_FAILED',
}

export enum EditLinkActionTypes {
  EDIT_LINK_DATA = 'EDIT_LINK_DATA',
  EDIT_LINK_FAILED = 'EDIT_LINK_FAILED',
  EDIT_LINK_SUCCESS = 'EDIT_LINK_SUCCESS',
}

export enum LoadLinkActionTypes {
  LOAD_LINK_DATA = 'LOAD_LINK_DATA',
  LOAD_LINK_FAILED = 'LOAD_LINK_FAILED',
  LOAD_LINK_SUCCESS = 'LOAD_LINK_SUCCESS',
}

export enum LoadLinksActionTypes {
  LOAD_LINKS_SUCCESS = 'LOAD_LINKS_SUCCESS',
  LOAD_LINKS_FAILED = 'LOAD_LINKS_FAILED',
  LOAD_LINKS_DATA = 'LOAD_LINKS_DATA',
}

export enum LoadSearchedLinkActionTypes {
  LOAD_SEARCHED_LINK_SUCCESS = 'LOAD_SEARCHED_LINK_SUCCESS',
  LOAD_SEARCHED_LINK_FAILED = 'LOAD_SEARCHED_LINK_FAILED',
  LOAD_SEARCHED_LINK_DATA = 'LOAD_SEARCHED_LINK_DATA',
}

export enum LoadSearchedLinksActionTypes {
  LOAD_SEARCHED_LINKS_SUCCESS = 'LOAD_SEARCHED_LINKS_SUCCESS',
  LOAD_SEARCHED_LINKS_FAILED = 'LOAD_SEARCHED_LINKS_FAILED',
  LOAD_SEARCHED_LINKS_DATA = 'LOAD_SEARCHED_LINKS_DATA',
}
